 apiVersion: networking.k8s.io/v1
 kind: ingress
 metadata:
    name: ingress-ngnix
    namespace: sock-shop
 spec:
    ingressClassName: nginx
    rules:
      - host: senaike.shop
        http:
          paths:
            - pathType: Prefix
              backend:
                service:
                  name: front-end
                  port:
                    number: 80
              path: /
